### PR TITLE
Remove people which have been completely deleted in MiData

### LINKED ISSUE #43: Removing of personal Information when a Person is deleted in Midata
### Summary
When a person is deleted in MiData, all personal information about this perso in HealthCheck must also be deleted. 

### Motivation & Use-Case
Nach dem schweizerischen Datenschutz kann eine Person von der PBS als Datenbearbeiter verlangen, dass ihre persönlichen Daten gelöscht werden («Löschungsbegehren»). In der Mitgliederdatenbank wurde ein entsprechender Prozess aufgesetzt, mit dem solchen Anfragen bearbeitet werden können, dieser führt zu einer Löschung des Datensatzes der Person in der Mitgliederdatenbank.
Damit die PBS dem Löschungsbegehren vollständig nachkommen kann, müssen persönliche Daten, die via Schnittstelle an HealthCheck übertragen wurden, ebenfalls gelöscht werden.

In den Informationen zum Datenschutz des HealthCheck schreibt die PBS aus diesem Grund:
`Wird eine Person in der MiData vollständig gelöscht, so werden alle persönlichen Daten dieser Person im HealthCheck ebenfalls gelöscht (Name, Adresse, Geburtsdatum, Geschlecht); sie bleibt dann nur noch als Zahl (+1) in den aggregierten Daten (bspw. Anzahl Teilnehmende eines bestimmten Jahrganges etc.) sichtbar, sofern diese Aggregation vor der Löschung stattgefunden hat.
`

Die Analyse des HealthCheck-Codes eines engagierten Mitglieds hat gezeigt, dass im Importprozess aktuell nur Personen hinzugefügt oder aktualisiert werden. Personen, die nicht mehr im Datensatz der PBS sind, werden im HealthCheck jedoch nicht gelöscht. 
[(https://github.com/digio-ch/pbs-healthcheck-core/blob/38b1c44632adc20c50ca7686bd66e620482324fe/src/Command/ImportFromJsonCommand.php#L548)](https://github.com/digio-ch/pbs-healthcheck-core/blob/38b1c44632adc20c50ca7686bd66e620482324fe/src/Command/ImportFromJsonCommand.php#L548-L555)

### Acceptance Criteria
- [ ] Personen, die beim Import nicht mehr im Datensatz sind, der von der Mitgliederdatenbank kommt, werden im HealthCheck ebenfalls gelöscht.
- [ ] Aggregierte Informationen, bspw. die Anzahl Personen in einer Stufe zum Zeitpunkt X, sind weiterhin verfügbar (diese würden erst verloren gehen, wenn der ganze Datensatz neu aufgebaut werden müsste)

### PR DESCRIPTION
**Pull request by carlobeltrame**
Fixes #43 
Not yet tested with real data.

This will also delete people which have gotten all their healthcheck-relevant roles hard deleted in MiData, which can happen in some exceptional cases.

I still think #28 would be way cleaner, and would make this band-aid fix obsolete.

### CODE REVIEW

**Comment by TaminoWalter** [comment]
@carlobeltrame this pull request is a draft for quite a while, are you still working on this? or do you need help with something?

**Comment by carlobeltrame** [comment]
I haven't gotten around to testing this extensively, that's why it's still a draft. But maybe we have to answer a question first:

Due to a database constraint, I had to also delete all roles, qualifications and event participations of such deleted people. MiData should do the same when completely deleting a person. But this might lead to inconsistencies with the aggregated data, because there the numbers still reflect these old roles. Is that okay, is that the way it's supposed to work?

**Comment by vouillamoz** [comment]
@carlobeltrame Thanks for your comment. From my point of view, the stated behavior might be part of the business requirements.  Removing the anonymized count of deleted subjects requires additional work and recomputation of the existing statistics. 

@taruxtin can you please decide what to do here?

**Comment by taruxtin** [comment]
From "business" side, we can accept these inconsistencies. It should only affect very few cases.

**Comment by TaminoWalter** [comment]
@carlobeltrame what is your estimation for when you can finish this? we will make a staging release next week and it would be great if we can include this feature

**Comment by carlobeltrame** [comment]
Theoretically the code is finished, but as stated in the description, I didn't get around to testing it manually yet, and I won't have time for that until next week. Feel free to test it yourself.

**Comment by vouillamoz** [comment]
@TaminoWalter please test, fix if needed, and integrate into develop.

**Comment by TaminoWalter** [comment]
@carlobeltrame I checked your code and noticed that you used nested for loops to go over the persons in the hc db and the ones that come from midata. This results in `person_count^person_count` iterations. I improved this by using a key value array which results in only `3*person_count` iterations.

The other parts of your merge request looked mostly good. 

I created a new pull request #65 with my improvements to your code and I will close this pull request.

Thank you for your contribution to the healthcheck project!

**Pull request closed without merging**
